version: "3.9"

services:
  communication-service:
    build: .
    container_name: communication-service
    ports:
      - "4004:4004"
    restart: always
    networks:
      - shared-net

networks:
  shared-net:
    external: true
    name: gateway_app-net
