services:
  communication-service:
    container_name: communication-service
    build: .
    env_file:
      - /home/deploy/config/.env.common
      - .env.staging
    ports:
      - "4004:4004"
    restart: always
    networks:
      - gateway_app-net

networks:
  gateway_app-net:
    external: true
